services:
  # Backend API Service
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: todo-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - sqlite_data:/app/data
    environment:
      - NODE_ENV=production
      - PORT=3000
    networks:
      - todo-network

  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: todo-frontend
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - backend  # Simple dependency without health check condition
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=8080
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - todo-network

volumes:
  sqlite_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/bchokri/Desktop/TodoList_fastify_Version/data

networks:
  todo-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16