
filebeat.inputs:
- type: filestream
  id: ft-transcendence-docker-logs
  enabled: true
  paths:
    - /var/lib/docker/containers/*/*.log
  
  parsers:
    - container:
        stream: all

processors:
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"
  - add_fields:
      target: fields
      fields:
        environment: development
        project: ft_transcendence

output.logstash:
  hosts: ["logstash:5044"]